<<<<<<< HEAD
# Generated by Django 5.0 on 2024-03-23 21:36
=======
# Generated by Django 5.0.1 on 2024-03-24 06:15
>>>>>>> 3761babbe7cc10c194ab5ef1bd31389cba865916

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='LinesForTyping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Character', models.CharField(max_length=25)),
                ('Line', models.TextField()),
=======
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_id', models.CharField(max_length=50, unique=True)),
>>>>>>> 3761babbe7cc10c194ab5ef1bd31389cba865916
            ],
        ),
    ]
