# Generated by Django 5.0.1 on 2024-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trollapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='game_mode',
            field=models.CharField(default='Floyd', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='num_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='lobby',
            name='privacy',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
