# Generated by Django 5.0.1 on 2024-03-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trollapp', '0003_rename_lobby_id_lobby_lobby_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='id',
        ),
        migrations.AddField(
            model_name='lobby',
            name='lobby_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
