# Generated by Django 5.0.1 on 2024-03-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trollapp', '0005_alter_lobby_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
