# Generated by Django 5.0.3 on 2024-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trollapp', '0007_remove_lobby_lobby_id_lobby_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='playersJoined',
            field=models.IntegerField(default=1),
        ),
    ]
